### PR TITLE
remove D_LOOKUP table

### PR DESCRIPTION
**Pull request by Casper-Guo**
This hard-coded table is out of date and doesn't seem to be used anywhere.

### CODE REVIEW

**Comment by theOehrly** [comment]
Technically this is public API even though it's not in the documentation. I think we could probably skip a proper deprecation here. Do you know if or how this was last used anywhere?

**Comment by Casper-Guo** [comment]
I can find two places in the git history where this table was used.

The table was first added in this [commit](https://github.com/theOehrly/Fast-F1/commit/32b802d935dd91f98f13493cb1da5a7c8a5c55d2) back in February 2020 for compatibility with 2020 winter tests. The original use case was removed in this [commit](https://github.com/theOehrly/Fast-F1/commit/cd606bba45a08f872e2525fb4382014d6cb73196) in July 2020 but a new dependency was added. That dependency was removed [here](https://github.com/theOehrly/Fast-F1/commit/0dac6b4e9928249a882d5e898de94d8d6d7c77fd#diff-031170af7564bd3cd597c2e7c06f73dbe238f98788257ca7279d231d85e22244) in March 2022. **This is the last time I can find `D_LOOKUP` in any diff.**

The second use case is added [here](https://github.com/theOehrly/Fast-F1/commit/bcc761a299abdf8ab42c4178f735c9353be1de58) in November 2020 to reimplement driver ahead calculation. The usage is fairly trivial. This dependency is removed less than a month later in this [commit](https://github.com/theOehrly/Fast-F1/commit/ae5f14668815ece316fb9fe0050846ad8dd0fc59).

So this table was never used extensively anywhere. And we have not needed it for the last two years.

**Comment by Casper-Guo** [comment]
Ran pylint to find if we have other unused variables like that but seems like we are pretty good about that issue. I just looked over the output and fixed a few minor things.

**Comment by theOehrly** [comment]
OK, thanks for the investigation. Given that it was only ever used internally, never documented and is long out of date and therefore basically useless, I'll say it's fine to skip a proper deprecation here.

**Pull request merged**
