### PR TITLE
Team pace ranking example

### PR DESCRIPTION
**Pull request by Casper-Guo**
Produce the following plot:

team_pace

### CODE REVIEW

**Comment by Casper-Guo** [comment]
The `SettingWithCopyWarning` is a false positive

Can be disabled with `pd.options.mode.chained_assignment = None`

**Comment by theOehrly** [comment]
> The `SettingWithCopyWarning` is a false positive

It's not really a false positive. It's complaining because ``.pick_quicklaps`` is returning a copy of  ``race.laps``. So you are not modifying the original ``race.laps``.  Which also isn't the intention here, but the warning is distracting.

I don't really want to disable the warning in pandas entirely. You'd need to explain that line of code as well then. 
It would be possible to hide it (https://sphinx-gallery.github.io/stable/configuration.html#hiding-lines-of-code) but that's not really a good solution either, I think. 

Maybe the best solution would be to slightly modify the example so that the problem does not occur? Is that possible without making the code much more complicated? Just don't create the column in the exisiting dataframe but keep the data as a separate variable or create a new DataFrame? What do you think?

**Comment by Casper-Guo** [comment]
Should be a very simple modification, will look into it

**Comment by Casper-Guo** [comment]
Got rid of the warning, everything looks decent in the build now

**Comment by Casper-Guo** [comment]
Yes I forgot that detail. I've edited all the block comments.

**Comment by theOehrly** [comment]
All good now, in my opinion. I can merge this? Or is there anything you want to change still? I'm a bit confused by your comment about the typo 😅

**Comment by Casper-Guo** [comment]
Ah sorry I forgot to update the comment after my last push. Everything ready to merge now.

**Pull request merged**
