### PR TITLE
Updated driver colors based on 2023 team rosters

### PR DESCRIPTION
**Pull request by Casper-Guo**
See #324 

Updated plotting information to reflect the 2023 season F1 roster.

### CODE REVIEW

**Comment by Casper-Guo** [comment]
Drugovich drove for Aston Martin in testing. Not sure if how similar situations are handled in the past and whether he should be included.

**Comment by theOehrly** [comment]
In the past, reserve drivers have been included if they drove in a session for which timing data is available. So it would be good if you can add Drugovich as well.

**Comment by Casper-Guo** [comment]
Drugovich added. The test failure appears unrelated

**Comment by theOehrly** [comment]
DEV is incorrectly keyed to Pierre Gasly in the driver translate dictionary.

Test failure was unrelated and caused externally. Passing now, as expected.

**Comment by theOehrly** [comment]
Looks good now, thank you for getting this done this quick.

**Pull request merged**
