### PR TITLE
Fixed HeadshotUrl in driver_info

### PR DESCRIPTION
**Pull request by bruzie**
Beginning with Miami 2022, HeadshotUrl information are separate entries in DriverInfo.jsonStream (one entry per team, MAG still missing). For example:

```
00:00:03.281{"1":{"RacingNumber":"1","BroadcastName":"M VERSTAPPEN", ... "Line":20}}
00:00:09.339{"1":{"TeamName":"Red Bull Racing","TeamColour":"1e5bc6","FirstName":"Max" ... "CountryCode":"FIN"}}
00:00:09.339{"1":{"HeadshotUrl":"https://www.formula1.com/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png.transform/1col/image.png"},"11":{"HeadshotUrl":"https://www.formula1.com/content/dam/fom-website/drivers/S/SERPER01_Sergio_Perez/serper01.png.transform/1col/image.png"}}
```

This update adds support for these entries and bundles them into the driver_info dictionary. Older sessions with all driver info bundled into the one entry still work.

### CODE REVIEW

**Comment by theOehrly** [comment]
Hi, I'll try to take a look at this later today. Or tomorrow at the latest.

**Comment by theOehrly** [comment]
Looks good. Just to confirm, the api response changed just now? But the change affects older sessions as well, right? If I request data for one of the 2021 session now, for example, then the fix from this PR is still required to load the headshot urls.

**Comment by theOehrly** [comment]
Ok, can you just add a comment, to note that this data might be contained within one single entry or that there might be separate entries?

**Comment by bruzie** [comment]
Argh, accidentally committed my updated version file and messed things up trying to undo. Hopefully it's better now.

**Comment by theOehrly** [comment]
Looks good to me

**Comment by theOehrly** [comment]
Thank you, I hadn't even noticed this problem yet.

**Pull request merged**
