### PR TITLE
Fix Misclassification of Laps in 'split_qualifying_sessions' Method

### PR DESCRIPTION
**Pull request by tmossington**
Hi!

I fixed a bug associated with laps being misclassified into an earlier qualifying session because the driver passed the timing beam, as reported here: (https://github.com/theOehrly/Fast-F1/issues/605#issue-2381081866).

Happy to make any changes necessary to make sure my changes comply with the testing and documentation requirements.

Summary:
This PR introduces a new method, 'correct_lap_placement', to address an issue where laps are incorrectly classified into earlier qualifying sessions when a driver enters the pits and crosses the timing beam before the start of the next session. The fix ensures that such laps are reassigned to the correct qualifying session, improving the accuracy of the 'split_qualifying_sessions' method.

Changes Made:

- New Function: Added 'correct_lap_placement(self, laps, split_times)', which:

    Identifies laps that end in the pits and checks if the driver exits the pits after the start of the next qualifying session.

    Reassigns these laps to the correct session, ensuring they are not misclassified as part of an earlier session.

    Maintains the original column order and handles edge cases like empty or all-NA entries.

- Integration: Integrated 'correct_lap_placement' into the existing 'split_qualifying_sessions' method to automatically correct any misclassified laps before returning the final split sessions.

Issue Addressed:
- Problem: When using the 'split_qualifying_sessions' and 'pick_drivers' methods, laps were not correctly split between qualifying sessions. For example, Lap 15 (which should be classified as a Q2 lap), was incorrectly placed into Q1, and Lap 18 (which should be a part of Q3), was placed into Q2.

Impact:
- This fix will correct the classification of laps across qualifying sessions, improving the accuracy of data analysis and reporting in FastF1.

### CODE REVIEW

**Comment by theOehrly** [comment]
@tmossington thank you for having a look at this problem. Your solution really looks nicely written and well documeted.
I'd really prefer if there was a less complex solution to this though. The code is fairly involved and having two nested for loops over the number of laps is also not a very performant solution.

I was really hoping that this could be resolved by changing the logic here:

https://github.com/theOehrly/Fast-F1/blob/95f623184b8d8cb41f4b7a0060f797a10e7b300d/fastf1/core.py#L3343-L3349

It might not be possible to keep this as one line assignment with including the logic. But hopefully we'd be able to keep it fairly concise.

Given that you have already looked at the issue, you probably understand the problem well now. Maybe you can try and fix it by changing that specific part of the existing code. Of course, if that is not viable, maybe we need to use the solution that you have already worked out. But I'd really hope that we can simplify this a bit more.

Feel free to ask if you have any more questions.

**Comment by tmossington** [comment]
Sure thing, reducing the looping to improve performance makes sense. I'll take a look at this later today and see if I can come up with a solution that modifies this block:

> https://github.com/theOehrly/Fast-F1/blob/95f623184b8d8cb41f4b7a0060f797a10e7b300d/fastf1/core.py#L3343-L3349

Thanks for the feedback, I'll let you know what I'm able to do about this!

**Comment by theOehrly** [comment]
@tmossington awesome, thank you :)

**Comment by tmossington** [comment]
So, I played around with it some today and have come up with a bit of a different solution. I'm not sure if this solution is actually better, but it does condense things down a bit and I aimed to follow the style of the existing code (although I was unable to get it to work with just a line or two). 

It works in much the same way as the initial method, except instead of using a for loop to iterate over every lap, it uses the same vectorized boolean indexing to identify laps that meet the "mistake" criteria:

1. The driver entered the pits on the previous lap
2. The driver left the pits on this lap
3. The next lap begins in the following qualifying session
4. This lap started prior to Q3 (as laps do not need to be adjusted from Q3).

Then, the "mistake" laps are removed from the current_laps variable, and laps[I] is populated with the values in current_laps. Finally, if the "mistake" laps variable is not empty, it will add these laps to the following qualifying session.


If you like this version, I already pushed changes to the same branch, so I think it should be ready. If not, I can revert it to the previous version or I can meddle with this one more! Apologies if it's still a bit unpolished.


```python
for i in range(len(split_times) - 1):
            # split by start time instead of end time, because the split times
            # that are generated from timing data may not account for crashed
            # cars being returned or having a generated lap time that results
            # in a late 'Time' value!

            # Find all of the appropriate laps for the current session and
            # assign them to current_laps
            current_session = (
                (self['LapStartTime'] > split_times[i]) &
                (self['LapStartTime'] < split_times[i + 1])
            )
            current_laps = self[current_session]

            # Find all of the laps that have been added to the
            # wrong qualifying session
            #(i.e. car passes timing beam in pits, initializing a new lap
            # but not finish said lap until the next session)
            next_session_criteria = (
                (~pd.isna(self['PitInTime'].shift(1))) &
                (~pd.isna(self['PitOutTime'])) &
                (self['LapStartTime'].shift(-1) > split_times[i + 1]) &
                # Verify session starts before Q3
                (self['LapStartTime'] < split_times[2])
            )
            # Align indices to avoid reindexing warnings
            next_session_criteria = \
                next_session_criteria.reindex(current_laps.index,\
                                              fill_value=False)
            # Grab all the laps in current_laps that fit the criteria
            next_session_laps = current_laps[next_session_criteria]

            # Remove laps that fit criteria from current_laps
            current_laps = current_laps[~next_session_criteria]

            # Accumulate laps in the current session
            laps[i] = pd.concat([laps[i], current_laps],\
                                 ignore_index=False).sort_index()

            # Assuming at least one lap meet criteria:
            if not next_session_laps.empty:
                # Always concatenate to the next session
                if i + 1 < len(laps):
                    laps[i + 1] = pd.concat([laps[i + 1], next_session_laps],\
                                            ignore_index=False).sort_index()

        # Remove any empty DataFrames
        laps = [session_laps if not session_laps.empty else \
                None for session_laps in laps]
        return laps
```


Some adjustments have been made to the original bit of code (initializing current_laps with the current session instead of immediately populating laps[i]):

```python
for i in range(len(split_times) - 1):
            # split by start time instead of end time, because the split times
            # that are generated from timing data may not account for crashed
            # cars being returned or having a generated lap time that results
            # in a late 'Time' value!

            # Find all of the appropriate laps for the current session and
            # assign them to current_laps
            current_session = (
                (self['LapStartTime'] > split_times[i]) &
                (self['LapStartTime'] < split_times[i + 1])
            )
            current_laps = self[current_session]
```

And then this is the block that's been added:

```python
# Find all of the laps that have been added to the
            # wrong qualifying session
            #(i.e. car passes timing beam in pits, initializing a new lap
            # but not finish said lap until the next session)
            next_session_criteria = (
                (~pd.isna(self['PitInTime'].shift(1))) &
                (~pd.isna(self['PitOutTime'])) &
                (self['LapStartTime'].shift(-1) > split_times[i + 1]) &
                # Verify session starts before Q3
                (self['LapStartTime'] < split_times[2])
            )
            # Align indices to avoid reindexing warnings
            next_session_criteria = \
                next_session_criteria.reindex(current_laps.index,\
                                              fill_value=False)
            # Grab all the laps in current_laps that fit the criteria
            next_session_laps = current_laps[next_session_criteria]

            # Remove laps that fit criteria from current_laps
            current_laps = current_laps[~next_session_criteria]

            # Accumulate laps in the current session
            laps[i] = pd.concat([laps[i], current_laps],\
                                 ignore_index=False).sort_index()

            # Assuming at least one lap meet criteria:
            if not next_session_laps.empty:
                # Always concatenate to the next session
                if i + 1 < len(laps):
                    laps[i + 1] = pd.concat([laps[i + 1], next_session_laps],\
                                            ignore_index=False).sort_index()

        # Remove any empty DataFrames
        laps = [session_laps if not session_laps.empty else \
                None for session_laps in laps]
```

**Comment by theOehrly** [comment]
I'll try to properly review this on the weekend. Hopefully I'll have enough time. Else, it might take a few more days.

**Comment by tmossington** [comment]
No worries, no rush on this!

**Comment by theOehrly** [comment]
Ok, my only real concern with this is the complexity of the logic. I'd really prefer to simplify that over your approach, Because event though the code is nicely written and commented, it's really not that straightforward to understand what's going on. Especially since we are dealing with a minor edge case, sort of.

I've made a "counterproposal" for how this could maybe be handled. Please have a look at it. Maybe I'm missing something obvious. I've decided to just commit it to another branch, so you can look at the diff of the changes here: https://github.com/theOehrly/Fast-F1/commit/b674282ccb6f663ca3f995df479dbc86bc0948a3

**Comment by tmossington** [comment]
So I took a look, and everything looks good here. I actually think your solution beats mine both on simplicity and performance, as direct assignment should be faster than concatenating. I also didn't do extensive testing of your version, but I tested it on the original issue and several other qualifying sessions that have unusual laps, and it seems to handle everything thrown at it. Sorry to make you do the work in the end, but hopefully my solution helped move it in the right direction!

**Comment by theOehrly** [comment]
Don't worry at all, I'm rather sorry that I probably won't be able to merge your PR then. Even though it looks like you really spent a lot of effort on this.
But in any case, seeing another solution, discussing the problem and having a second set of eyes on everything is great. And I also enjoy reviewing PRs and giving suggestions.

By the way, which other qualifying sessions are you aware of, where this is a problem?

I'll do a bit more thorough testing on both solutions and check against a potential edge case that I thought of. And then I'll decide how to proceed.

**Comment by tmossington** [comment]
Sorry for the late response, lot of travel last week!

No worries about the PR, it's more important that the best solution is used. Plus, just collaborating on code makes me a stronger programmer so I'm happy. I'll keep an eye on the issues page for other things I can work on, or if you have any ideas of improvements needed feel free to drop me a message.

 I only tested a few other qualifying sessions, but it seemed like much of 2024 sessions had this issue (Spa, Imola, Monza, Zandvoort, etc.). I suspect it's a fairly widespread problem, but your solution looks like it passes all of these sessions.

**Comment by theOehrly** [comment]
I've implemented my solution now, after further testing. Thank you again for your input on this!

> I'll keep an eye on the issues page for other things I can work on, or if you have any ideas of improvements needed feel free to drop me a message.

Always appreciated :) Although, I think there are few good issues at the moment. Most stuff is blocked due to external constraints or is part of larger refactoring tasks.

**Pull request closed without merging**
