### PR TITLE
Add drivers standings. Improve example.

### PR DESCRIPTION
**Pull request by oscr**
Part of #229 

I experimented a little with making it a pandas Dataframe but it was kind of tricky with the (standings response)[http://ergast.com/mrd/methods/standings/]. Both that we want a very strict subset of the response `data['MRData']['StandingsTable']['StandingsLists'][0]['DriverStandings']`, but still then the data is a list of dicts with nested dicts (such as Driver and Constructors). 

I tried to flatten the DF. I tried variants `pandas.DataFrame.from_dict()` etc but didn't I didn't get it a into a nice format. Another thought that I had was: even if I manage to make it a Dataframe. Will the `calculate_who_can_win` function be better with it? Would those types of calculations be improved?

### CODE REVIEW

**Comment by theOehrly** [comment]
In general, I think this should be converted to a DataFrame, yes. For example, currently, to get a simple information like who has more than x points, you'd need to loop over all entries of the result. A DataFrame will simplify all sorts of sorting, indexing, filtering and math operations greatly.

Driver and Constructor are the only nested entries. I'd simply reduce these to driver number, driver abbreviation and team name (equivalent to the columns in `Laps`). Separate API endpoints are available to get the extended information exclusively. 

Alternative 1: the data could be flattened completely to include all the information in one single flat DataFrame.

Alternative 2: the additional information is stored into two separate driver and constructor DataFrames which are linked to the standings dataframe. Two methods `get_driver_information` and `get_team_information` are provided on the standings DataFrame. These will return the additional data. If the standings df is sliced, the additional data is only returned for those drivers/teams that are still contained in the sliced standings df. The Series representation of the standings DataFrame gets the same two methods added. These will then only return the appropriate Series with extended information for one driver or team.
This is the really fancy (and maybe overkill) approach.

I just now also found:

1. https://github.com/weiranyu/pyErgast : Converts everything to pandas as well. Doesn't seem to be maintained well though, see the open PR for sprint race support.

2. https://github.com/BrozenSenpai/yukinator : Uses its own data objects. IMO, this has the same issues as the list representation, mainly, no easy indexing, sorting, math operations.

**Comment by oscr** [comment]
So to get a practical example, if we look at one of the drivers from 
https://ergast.com/api/f1/2022/driverStandings.json:
```
{"position":"1","positionText":"1","points":"341","wins":"11","Driver":{"driverId":"max_verstappen","permanentNumber":"33","code":"VER","url":"http:\/\/en.wikipedia.org\/wiki\/Max_Verstappen","givenName":"Max","familyName":"Verstappen","dateOfBirth":"1997-09-30","nationality":"Dutch"},              "Constructors":[{"constructorId":"red_bull","url":"http:\/\/en.wikipedia.org\/wiki\/Red_Bull_Racing","name":"Red Bull","nationality":"Austrian"}]}
```

Returning it as a dictionary with nested dictionaries works out of the box. Maybe it's something the user might want an option to *also* get it as is? 

To make the payload a dataframe there are some choices needed: 
* Flatten: what should nested fields be called? Both driver and constructors have `url` field. So that field would have to be called `driver_url` and `constructors_url`?
* Dropping constructor (and maybe keeping (`constructorId`?) and just merging the driver and standing data into a dataframe.

What's your opinion about above?

Also as a side note: now when we have default caching maybe we should consider removing `fastf1.Cache.enable_cache("../doc_cache") ` from the examples? I ran the example from outside examples folder and it failed since it didn't find the `doc_cache` folder because it's a relative path. Just running the examples is something beginners without a configured environment would do so maybe it would be better to ensure it works out of the box.

**Comment by theOehrly** [comment]
> Returning it as a dictionary with nested dictionaries works out of the box. Maybe it's something the user might want an option to _also_ get it as is?

Agree, this is probably a very good idea.

> To make the payload a dataframe there are some choices needed:
> 
>     * Flatten: what should nested fields be called? Both driver and constructors have `url` field. So that field would have to be called `driver_url` and `constructors_url`?
> 
>     * Dropping constructor (and maybe keeping (`constructorId`?) and just merging the driver and standing data into a dataframe.

I'd go with flatten and keep both. Duplicate keys from nested dictionaries get the key of the dictionary added as a prefix (as you suggested). With this rule, it'd hopefully be possible to have one internal `flatten_to_df` function that handles all returned data.

Furthermore, I had some ideas for how a unified interface to Ergast could look like. In general, Ergast allows filtering by specific attributes and one single attribute can then be listed. For example:

- `/drivers` lists all drivers
- `/drivers/alonso/constructors` filter by driver=alonso: list all constructors
- `/2010/5/drivers/alonso/qualifying` filter by sesaon=2010, round=5, driver=alonso: list qualifying results

One could create an `Ergast` object where this could be implemented in one of the following ways (just some examples)

```
ergast = Ergast()

# idea 1
ergast.filter(driver='alonso').get_constructors()

ergast.filter(sesason=2010, round=5, driver='alonso').get_qualifying()
ergast.filter(sesason=2010, round=5, driver='alonso').get_qualifying(raw=True)  # return dict object


# idea 2
ergast.driver('alonso').constructor().get()

ergast.season(2010).round(5).driver('alonso').session('qualifying').get()
ergast.season(2010).round(5).driver('alonso').session('qualifying').get(raw=True)  # return dict object
ergast.season(2010).round(5).driver('alonso').session('qualifying').get_dict()  # return dict object (alternative)

```
Of course, there a likely many other ways that this could be structured. What I'd aim for is that as much information as possible about the available API calls is available through auto-complete/introspection.

------------------------
 
> Also as a side note: now when we have default caching maybe we should consider removing `fastf1.Cache.enable_cache("../doc_cache") ` from the examples? I ran the example from outside examples folder and it failed since it didn't find the `doc_cache` folder because it's a relative path. Just running the examples is something beginners without a configured environment would do so maybe it would be better to ensure it works out of the box.

Yes, absolutely. This needs to be done before the next release.

**Comment by oscr** [comment]
> > Returning it as a dictionary with nested dictionaries works out of the box. Maybe it's something the user might want an option to _also_ get it as is?
> 
> Agree, this is probably a very good idea.

This turned out to be pretty simple: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_dict.html#pandas.DataFrame.to_dict almost so simple it might not need to be implemented. Just mentioning it somewhere might be enough. 

> 
> > To make the payload a dataframe there are some choices needed:
> > ```
> > * Flatten: what should nested fields be called? Both driver and constructors have `url` field. So that field would have to be called `driver_url` and `constructors_url`?
> > 
> > * Dropping constructor (and maybe keeping (`constructorId`?) and just merging the driver and standing data into a dataframe.
> > ```
> 
> I'd go with flatten and keep both. Duplicate keys from nested dictionaries get the key of the dictionary added as a prefix (as you suggested). With this rule, it'd hopefully be possible to have one internal `flatten_to_df` function that handles all returned data.

Another thing that turned out really easy: https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html

After looking at it the first time I thought I was going to be a huge pain. But turned out to work out of the box.

> Furthermore, I had some ideas for how a unified interface to Ergast could look like. In general, Ergast allows filtering by specific attributes and one single attribute can then be listed. For example:
> 
>     * `/drivers` lists all drivers
> 
>     * `/drivers/alonso/constructors` filter by driver=alonso: list all constructors
> 
>     * `/2010/5/drivers/alonso/qualifying` filter by sesaon=2010, round=5, driver=alonso: list qualifying results
> 
> 
> One could create an `Ergast` object where this could be implemented in one of the following ways (just some examples)
> 
> ```
> ergast = Ergast()
> 
> # idea 1
> ergast.filter(driver='alonso').get_constructors()
> 
> ergast.filter(season=2010, round=5, driver='alonso').get_qualifying()
> ergast.filter(season=2010, round=5, driver='alonso').get_qualifying(raw=True)  # return dict object
> 
> 
> # idea 2
> ergast.driver('alonso').constructor().get()
> 
> ergast.season(2010).round(5).driver('alonso').session('qualifying').get()
> ergast.season(2010).round(5).driver('alonso').session('qualifying').get(raw=True)  # return dict object
> ergast.season(2010).round(5).driver('alonso').session('qualifying').get_dict()  # return dict object (alternative)
> ```
> 
> Of course, there a likely many other ways that this could be structured. What I'd aim for is that as much information as possible about the available API calls is available through auto-complete/introspection.

I liked the first alternative. It feels like a structure that you would intuitively think: what happens if I delete "round=5" or if I change "driver" to "team".

**Comment by theOehrly** [comment]
> > > Returning it as a dictionary with nested dictionaries works out of the box. Maybe it's something the user might want an option to _also_ get it as is?
> > 
> > 
> > Agree, this is probably a very good idea.
> 
> This turned out to be pretty simple: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_dict.html#pandas.DataFrame.to_dict almost so simple it might not need to be implemented. Just mentioning it somewhere might be enough.

This is not really what I had in mind. I thought that we'd just return the original Ergast response. Then, users can easily get the json response that is documented on ergast.com as a nested dict/list combination. If we use `DataFrame.to_dict()`, the structure of the response is lost and the dictionary will also be flattened.


> Another thing that turned out really easy: https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html
> 
> After looking at it the first time I thought I was going to be a huge pain. But turned out to work out of the box.

I fear it will still be a bit of a pain because `pandas.json_normalize`  does not actually work as necessary. Or rather, when taking a look at the docs, it does provide some flexibility but I think we cannot make it work as required here.

grafik

For example, with the driver standings specifically, `Constructors` is a list containing one or multiple constructor entries. You can see this in the 2016 season for example, with the switch between Verstappen/Kvyat in the Red Bull.
So, I fear that there will be more manual parsing involved. 

How to handle this is actually quite a problem in itself. Maybe it is necessary after all to drop some of the data, when converting to a dataframe. For example, we could do comma seperated values in the constructor name field and constructor id field. And then a seperate request is required to get the remaining constructor information independently of driver standings.


> I liked the first alternative. It feels like a structure that you would intuitively think: what happens if I delete "round=5" or if I change "driver" to "team".

I also prefer the first alternative. But I don't like that it leads to a huge number of differently named `get_*` methods. On the other hand, if it were just `get('qualifying')` one wouldn't have any idea what qualifying could be substituted with. So that's not a good alternative either.

What is your aim for this PR right now? I don't want to merge any changes to ergast.py when the plan is to completely rework the ergast interface in the very near future.

**Comment by oscr** [comment]
> This is not really what I had in mind. I thought that we'd just return the original Ergast response. Then, users can easily get the json response that is documented on ergast.com as a nested dict/list combination. If we use `DataFrame.to_dict()`, the structure of the response is lost and the dictionary will also be flattened.

That's even better. Let's do that.

> I fear it will still be a bit of a pain because `pandas.json_normalize` does not actually work as necessary. Or rather, when taking a look at the docs, it does provide some flexibility but I think we cannot make it work as required here.
> 
> grafik
> 
> For example, with the driver standings specifically, `Constructors` is a list containing one or multiple constructor entries. You can see this in the 2016 season for example, with the switch between Verstappen/Kvyat in the Red Bull. So, I fear that there will be more manual parsing involved.
> 
> How to handle this is actually quite a problem in itself. Maybe it is necessary after all to drop some of the data, when converting to a dataframe. For example, we could do comma seperated values in the constructor name field and constructor id field. And then a seperate request is required to get the remaining constructor information independently of driver standings.

That's a really good point that I actually never thought of. I'm sure that will be a surprise for most users :)

It looks like pandas handles this in an "ok" way. 

```python
>>> v = {"driver":"max", "constructors":[{"constructor":"a"},{"constructor", "b"}]}
>>> df = pandas.json_normalize(v, sep="_")
>>> df
  driver                              constructors
0    max  [{'constructor': 'a'}, {constructor, b}]
>>> df.iloc[0]['constructors']
[{'constructor': 'a'}, {'constructor', 'b'}]
```

It's maybe not the most fun thing to read, but given the amount of work required to get custom parsing working... Maybe it's "good enough" with some extra documentation and examples demonstrating this behavior? 

> > I liked the first alternative. It feels like a structure that you would intuitively think: what happens if I delete "round=5" or if I change "driver" to "team".
> 
> I also prefer the first alternative. But I don't like that it leads to a huge number of differently named `get_*` methods. On the other hand, if it were just `get('qualifying')` one wouldn't have any idea what qualifying could be substituted with. So that's not a good alternative either.
> 
> What is your aim for this PR right now? I don't want to merge any changes to ergast.py when the plan is to completely rework the ergast interface in the very near future.

My aim is to make the "who can win" and similar example as nice as possible for the user. Looking at what can be pushed into the framework and what do we expect from the users. Now this pr can wait for an ergest rewrite, use the old way, or implement the new way for new functionality as it is added. Whatever works best for you.

**Comment by theOehrly** [comment]
> It looks like pandas handles this in an "ok" way.
> 
> ```python
> >>> v = {"driver":"max", "constructors":[{"constructor":"a"},{"constructor", "b"}]}
> >>> df = pandas.json_normalize(v, sep="_")
> >>> df
>   driver                              constructors
> 0    max  [{'constructor': 'a'}, {constructor, b}]
> >>> df.iloc[0]['constructors']
> [{'constructor': 'a'}, {'constructor', 'b'}]
> ```
> 
> It's maybe not the most fun thing to read, but given the amount of work required to get custom parsing working... Maybe it's "good enough" with some extra documentation and examples demonstrating this behavior?

I'm really not a fan of this behaviour/solution. I don't think it works well with what users expect from data in a DataFrame. But I also don't have a convincing alternative at the moment. I need to think about this problem a bit more and try some stuff out.

> My aim is to make the "who can win" and similar example as nice as possible for the user. Looking at what can be pushed into the framework and what do we expect from the users. Now this pr can wait for an ergest rewrite, use the old way, or implement the new way for new functionality as it is added. Whatever works best for you.

Ok, I think then we keep this PR until the Ergast "problem" is solved.

**Comment by oscr** [comment]
> I'm really not a fan of this behaviour/solution. I don't think it works well with what users expect from data in a DataFrame. But I also don't have a convincing alternative at the moment. I need to think about this problem a bit more and try some stuff out.

I think this only becomes a problem if it comes as a total surprise for the user and there is no clear way to resolve it. If implemented we should have examples + docs that explicitly mention this. I prefer this over simplifying the data and losing "correctness".

Maybe making some draft prs with the different alternatives will help make it clearer the impact of alternative 1 & 2? Both can be tested and discussed side by side.

**Comment by theOehrly** [comment]
@oscr In my opinion, it is a reasonable approach to simplify the data so that it is well representable in a DataFrame. We don't need to mirror the structure of Ergast exactly. Instead, I want to make it easy to work with the data. This can involve restructuring the data. I also think that custom parsing is totally fine to achieve this goal.
Remember that we want to provide the original (raw) response as well. So the original structure is preserved there, for those users that prefer that.
It should be questioned though if a DataFrame is the right data structure for visualizing the data. If the data cannot be represented in a DataFrame then maybe it's not a good idea to try and fit it into a DataFrame.

**Comment by theOehrly** [comment]
Draft PRs to compare various ideas are probably a good idea. I'm playing around with some ideas as well and I'll create a draft PR once it sort of works.

**Comment by oscr** [comment]
The question becomes how do you simplify the data and pick a "correct" constructor?

* If a reserve driver drives two races for two different teams.
* If a driver drives e g 21 races for AT and then ends with 1 in RB. Is that a RB driver?
* If a driver drives 1 race for team A, 20 for team B and then 1 for team C. Is that a team C driver?

Also worth noting we're not getting much useful information from the constructors array with dicts: `"Constructors":[{"constructorId":"red_bull","url":"http:\/\/en.wikipedia.org\/wiki\/Red_Bull_Racing","name":"Red Bull","nationality":"Austrian"}]` So additional lookup would be needed anyway. Because I don't think any order is guaranteed from the api?

There might be more cases but what I wanted to argue is more or less: it's not really possible to simply the data to make everyone happy and it's going to be some work to get it working.

In a sense we are discussing the scope and use of FF1. I'm onboard with everything as a DataFrame. And I see great value in having a library that can abstract away the details of getting those DataFrames. The question becomes should FastF1 simplify the data at the cost of precision? And here I'm not fully convinced it should.

**Comment by theOehrly** [comment]
No data should be lost due to simplification, that's for sure. But there has to be a nicer way than this convoluted dictionary structure inside a DataFrame cell.
I'll try to get a draft for an idea of mine done by the end of the week. Then I'll open a draft PR for that. And we should then probably discuss the general approach in a separate issue if we are comparing multiple possible drafts.

**Comment by theOehrly** [comment]
@oscr I think we can close this PR? Ergast support has been added and you've updated the example, right? So everything here is done or out of date?

**Pull request closed without merging**
