### PR TITLE
Enhance add_sorted_driver_legend

### PR DESCRIPTION
**Pull request by formulatimer**
It would be useful if the function fastf1.plotting.add_sorted_driver_legend(ax, term) included the same arguments as the Matplotlib function ax.legend(), such as loc, fontsize...

Another improvement would be to ensure a unique list of labels

### CODE REVIEW

**Comment by theOehrly** [comment]
I agree with passing args and kwargs through to Matplotlib. We should do that. But I do not agree with ensuring uniqueness. Matplotlib's ``ax.legend()`` does not ensure unique labels either, so I don't think we should modify this part of the default behaviour.

**Comment by theOehrly** [comment]
The docstring also needs entries for args and kwargs then

**Comment by theOehrly** [comment]
I thought about this a bit more, and I think I see what you were aiming for in general. You are right that there is not enough customizability here right now.
The correct solution would probably be to explicitly take handles and labels as optional arguments and then only add those instead of getting all labels for the plot. The call signature for ``axes.legend`` is annoyingly convoluted and not that easy to overload.

**Comment by formulatimer** [comment]
When you call `add_sorted_driver_legend(ax, term)`, the only correct labels are drivers. Since plotting duplicate drivers makes no sense, I thought that unique label would be useful (at least for me)

I will add args and kwargs to the docstring

@theOehrly I saw you merge the new plotting module but no version has been released yet, how could I use the latest version of the plotting module?

**Comment by formulatimer** [comment]
Maybe this will not be the best solution for the future but for now is a very good solution and I need to customize the legend to adapt my code to the new plotting module. I would like to use the new plotting module in Belgium

**Comment by theOehrly** [comment]
> Maybe this will not be the best solution for the future but for now is a very good solution

The problem with that is that there should be API consistency. Changing the behaviour and function signature should be done with proper deprecation cycles, and those are slow. Therefore, I'd like to not need to touch this again soon.

I'll take the liberty to push a change to this branch and then merge (today and tomorrow). After the change, the function signature will behave exactly as ``axes.legend()`` from Matplotlib does. That means, you can pass customized handles and labels and remove duplicates by yourself before calling this function with a customized version of the handles and labels. This way, it works exactly as it would for vanilla Matplotlib.

My reasons for not doing deduplication in this function are that first, it might be surprising to other users because it doesn't match Matplotlib's behaviour. Second, if we do deduplication, there's no way around it. People cannot opt-out except if we add yet another argument and make the signature even more different from ``axes.legend()``. Now, by default duplicates will be kept. But users can manually remove duplicates beforehand.

**Comment by theOehrly** [comment]
The release will be tomorrow if I managed to verify and create a release with both Ergast and the F1 Livetiming API having problems right now.

**Pull request merged**
