### PR TITLE
Update RADME

### PR DESCRIPTION
**Pull request by peppe8o**
Added reference to a new tutorial about FastF1 on peppe8o.com with Raspberry PI

### CODE REVIEW

**Comment by theOehrly** [comment]
I've only had a short read over your blog post. Can you elaborate a bit on why you think that your tutorial is worth being added to the README file? What additional information does it offer over the existing documentation, examples, getting started section and over existing external tutorials?

**Comment by peppe8o** [comment]
Hi Philipp,
I think that my tutorial is worth to be added to your readme mainly because of the following reasons:
- it is specific for Raspberry PI users and based/tested on what that users have to do with RPI OS (see for example the note to add the python path)
- it is focused on people having low or no skills: it explains how to get the results with every line command and explaining the main concepts (my blog targets and aims to help these people)
- it is an "all in one page tutorial": within a single page, people with low experience can find all they need to get data and graphs

Of course, you are free to add or not in your readme file.

Best regards, Giuseppe

⁣Ottieni BlueMail per Android ​

Il giorno 1 Mag 2022, 13:17, alle ore 13:17, Philipp Schaefer ***@***.***> ha scritto:

**Comment by theOehrly** [comment]
I actually think that it may be confusing for people who are new to FastF1 and Python because your tutorial very specifically talks about the Raspberry Pi. Getting the hardware and setting up the system is not really related to FastF1. Also, the existing linked tutorials provide some good examples and the documentation has examples as well. Some of these are also fairly beginner-friendly.

**Comment by peppe8o** [comment]
I don't agreebut I respect your choose.
Cheers

⁣Ottieni BlueMail per Android ​

Il giorno 4 Mag 2022, 18:26, alle ore 18:26, Philipp Schaefer ***@***.***> ha scritto:

**Pull request closed without merging**
