### PR TITLE
DRS Value update

### PR DESCRIPTION
**Pull request by kwaters4**

### CODE REVIEW

**Comment by kwaters4** [comment]
#44 Pull request for some basic changes for now. Let me know if there is anything else needed. I do not think it is quite yet "fixed" due to some of the distinctions and values being unknown.

**Comment by kwaters4** [comment]
I will do some more when I have time. I just wanted to get things started! Thanks!

**Comment by theOehrly** [comment]
Hi, I'm not sure if I understood you correctly, actually. I would like to merge this because I think it is a very useful clarification. And I also think it's a very self-contained change. Did you want to add directly to this PR still? If not, I'll merge this, so I can actually update the docs.

**Comment by kwaters4** [comment]
Go ahead and merge it, I have been pretty busy, sorry!

**Pull request merged**
