### PR TITLE
Draft: Fix #165: session.laps.pick_fastest() should return the overall faste…

### LINKED ISSUE #165: [BUG] Personal best times need to be kept for each qualifying segment individually
### Discussed in https://github.com/theOehrly/Fast-F1/discussions/164

<div type='discussions-op-text'>

<sup>Originally posted by **blakehinsey** April 26, 2022</sup>
Has anyone noticed the behaviour of the pick_fastest() with Imola data for Qualifying?

I've looked into the code, and the only_by_time=True helps.

image

Does this mean that Q1 and Q2 laps were not counted as personal bests? It is a strange one as Q1/2 were dry and Q3 times were wet.

I will admit, my coding is not excellent, so maybe I have goofed something up.

It's "BRRRAKE" from Twitter btw!

</div>

The API resets personal best for every quali section. Only a reference to the last received personal best time is kept in the API parser. Therefore, Q3 overrides Q2 here despite the times being slower. This could actually happen in some dry sessions too, which is not good at all.

Working around this is non-trivial.The API parser needs to keep track of the order of personal best times to kind of create a ranking of official best times, while still detecting lap time deletions. Additionally, it needs to be possible to split the laps in `session.laps` into Q1, Q2 and Q3 laps.

### PR DESCRIPTION
**Pull request by AND2797**
…st lap, instead of the fastest lap in the latest session.

The personal best lap times are now additionally tracked in another column, 'historicalPersonalBest' which will let us pull the fastest legal lap across all sessions for any given event.

### CODE REVIEW

**Comment by AND2797** [comment]
I'll re run the tests. I think some tests are checking the size of the dataframe - since I added another column, the asserts need to be updated. I'll push a change for that.

**Comment by theOehrly** [comment]
I haven't really looked at this yet. But some tests will fail with the dataframe  being changed. You can ignore it for now, maybe we need to change something again. Then you need to update everything twice.

**Comment by AND2797** [comment]
Sounds good. I'll make the changes to the test after and if we agree this approach is fine!

**Comment by theOehrly** [comment]
Looking at this now, I agree that a boolean value is still good enough to mark the personal best laps. I currently don't see the benefit of keeping two columns for current and historical, though?  
The current column is equal to taking the last lap that is a historical personal best, no? So it'd be fine to just keep a single column where all personal best laps are marked as such. Do you agree or am I missing something?

**Comment by AND2797** [comment]
> Looking at this now, I agree that a boolean value is still good enough to mark the personal best laps. I currently don't see the benefit of keeping two columns for current and historical, though? The current column is equal to taking the last lap that is a historical personal best, no? So it'd be fine to just keep a single column where all personal best laps are marked as such. Do you agree or am I missing something?

I agree. There maybe a slight nuance that the "pole" position time will always be Q3 fastest time. If we mark everything as true in `personalBest` we won't have access to the pole position time without getting all the personal bests, and then checking with time.  This will obviously be resolved once we implement the new method where we split the lap times by Q1,Q2,Q3, then it should be easy to get the pole time (fastest in Q3), but in the interim period it will require some extra post-processing on the user side (should we choose to mark all personalBests as true). What do you think?

**Comment by theOehrly** [comment]
Ok, so this does not work correctly yet. You can not assume that the current lap is a personal best whenever a personal best value is received.
See, for example, Norris in the Spanish GP Qualifying:
grafik

The second to last lap (1:19.977) was deleted because  of track limits. After that, the API sends 1:20.471 *again*, which was the previous fastest lap. But the way you have it implemented currently, this is interpreted as the last lap being a fastest lap as well. You need to keep track of the actual personal best *values*, at least locally in the api parser. It's the only way you can detect if a fastest lap is deleted. You can then match these values to their respective laps and mark them as personal best.

**Comment by AND2797** [comment]
Okay, let me check this again!

**Comment by AND2797** [comment]
Will the API always send the previous legal lap immediately after a lap time is considered deleted? 

01:20.471
01:19.977 <-- deleted
01:20.471

Or is there any situation like below that can arise 

01:20.471
01:19.977 <-- deleted
01:18.850
01:20.471

I think the above case wouldn't make sense but just wanted to confirm API behavior. I was able to find what the issue was with my earlier implementation, I did not consider the deleted laps, and was updating bestLaps by lapcnt - but really we should be matching with the actual best lap times like you mentioned.

**Comment by theOehrly** [comment]
The answer is, I don't know for sure. But here is what I would expect. Consider that the timing data that FastF1 is downloading really just is a recording of the live timing data stream. Therefore, it would make sense that the personal best value directly updates what is displayed live in the app interface. 
I assume that if your second example situation occurs, we would not be able to detect that the lap was deleted. In my opinion, if a faster lap has already been set before the lap is deleted, no personal best value will be sent again because the currently displayed personal best value would not need to be updated. This is of course not ideal, but it is not a huge issue either because `.pick_fastest` would still return the correct lap. Usually nowadays, lap time deletions due to track limit violations are fairly quick and there shouldn't be any issues, though.

I would like to get the data as accurate as possible from this one data source. We might not be able to make it perfect, though. Parsing the race control messages **additionally**, to catch edge cases as well, could be considered after that. This would need to be done somewhere in `Session._load_laps`, so it can be added later separately.

One more edge case that we need to consider somehow is what happens if a driver's very first lap is deleted. Yes, this would be an outlap, and it is therefore not really relevant. But we need to make sure that there's no unhandled exception in case the personal best value is an empty value or something like that.

**Comment by AND2797** [comment]
Good points all. I think for now then we can assume that the previous lap time is sent again immediately if the current lap time is deleted?

I might need some more time to close this - as I'm busy with some IRL things. But if anyone else wants to pick it up in the meantime, I think our discussion should provide plenty background. I'll try to get back to this in a week or so.

**Pull request closed without merging**
