### PR TITLE
Improving the accuracy of utils.delta_time

### PR DESCRIPTION
**Pull request by grahamjwhite**
The `utils.delta_time` function can give inaccurate results. The reason is that it uses distance to compare the times of the two cars. What we really want is to compare how long it takes the two cars to reach the same _position on track_. The problem with using distance is that cars don't follow the exact same line and so travel different distances to reach the same position on track. To illustrate, consider two cars completing a lap. One car might travel 4010m and the other 4000m to reach the finish line. `utils.delta_time` would interpolate the second car's telemetry onto the first and compare the laptime of both cars at a distance of 4010m. But for the second car, 4010m is 10m past the finish line, and we are overestimating the laptime of the second car. 

Ideally we would be able to use the position data to evaluate how long it takes each car to reach the same position on track, but the position data are measured from noisy GPS signals which introduces other issues. 

A simpler approximation is to 'shrink' or 'expand' the distance data for one of the cars so that the total distance traveled over the lap is the same as the other car. This puts the distance data on a roughly comparable basis. The interpolation can then proceed as normal. 

To evaluate the change, we can calculate, for a particular race and for every possible driver pairing, the difference in laptime from the laps object and compare it to the final data point of the laptime delta produced by `utils.delta_time`. These should produce the same thing, which is the laptime delta at the end of the lap. Here is a chart of the distribution of 'errors' using the current version of `utils.delta_time` from the Brazilian Grand Prix:

current_delta_time

And here is the same thing using the amended version of `utils.delta_time` (note the scaling factor in the bottom right - the errors are practically zero):

improved_delta_time

This 'fix' is a close enough approximation that the `utils.delta_time` function should produce useful results without having to put a lot more effort into a more complicated procedure.

### CODE REVIEW

**Comment by theOehrly** [comment]
Hi, thank you for this pull request. I'll try to take a detailed look at this in the next few days. I want to compare the calculated delta with some analyses from other sources before going forward with this change. It really would be awesome to get this problem resolved finally. This has been on the ToDo list for way too long already.

As for the test failures:
- one failure is due to line length >79 characters
- the other failures are because one of the baseline images is now different due to this change. This is expected with this change. You can run ``pytest --mpl --mpl-generate-path=fastf1/tests/mpl-baseline fastf1/tests/test_example_plots.py:
:test_doc_example_delta_time`` from the project root directory to update the image. Development requirements need to be installed for that.

**Comment by grahamjwhite** [comment]
Thanks for looking at it. Understand you'll want to do some checks. If it helps, this method is similar to that used by the owner of the f1tempo site. You can see their response to a question on reddit here: [FastF1 library: How to improve calculation accuracy](https://www.reddit.com/r/F1Technical/comments/trsfu3/fastf1_library_how_to_improve_calculation_accuracy/). 

I've fixed up the test chart, will fix up the Ruff check soon.

**Comment by theOehrly** [comment]
I just took at quick look at this. And while this change fixes the end-of-lap differences (as you clearly showed), there are still high inaccuracies. 
The implementation now matches F1 Tempo more or less, I think. But there, the issue is the same. 
Have a look at this video: https://www.youtube.com/watch?v=TrBpiB5N298 (thats 2022, Round 19)
If you compare the deltas that are shown there with the deltas you get with FastF1/F1-Tempo, the absolute differences can be pretty big. The overall tendencies about who makes up time when are correct. But the absolute values are far from correct.

So this change is certainly an improvement. But it doesn't really fix the root problem with the ``delta_time`` function 😔

Correct me if I'm missing anything here.

**Comment by grahamjwhite** [comment]
Completely agree, and definitely don't think this 'fix' is the best that can be done, but it's also not mutually exclusive to other improvements you might consider. For example, even if someone came up with an interpolation method that performed better than what is currently used, this adjustment is likely to still be necessary. Another thing that might be impacting it is data points that are poor quality, but procedures for dealing with those can also be developed and implemented alongside this adjustment. 

I personally don't think we'll ever be able to get a completely satisfactory result with the sampling rate that we have available. Capturing braking/acceleration points accurately needs higher frequency data, so it's just a matter of getting as close as possible, and then deciding if you're comfortable enough with the accuracy to publish the function. 

If you or anyone else has other ideas for improving `delta_time` I'm happy to try to find some time to test it out. We could hold off on this PR until some other ideas have been tested if you prefer.

**Comment by theOehrly** [comment]
Awesome, thank you for this PR!

**Comment by grahamjwhite** [comment]
No problems. Happy to be able to contribute to a great project. Hopefully there will be some other ways I can chip in in future.

**Pull request merged**
