### PR TITLE
Animated example

### PR DESCRIPTION
**Pull request by UmiVilbig**
This python script gets the telemetry data but creates an animated lap around the circuit. Alongside the car going around the circuit, there are list of telemetry data which are also animated. At the end of the lap in the console, you will see an average and top speeds.

Its been a while since I brought up in ENH-325 and finally gotten around to it :)

### CODE REVIEW

**Comment by theOehrly** [comment]
Hey, really cool to have this added. A few things still need to be addressed, though.

First, the plot is currently shown right after the second code block:

<details><summary>Click to show</summary>

grafik

</details>

You need to defer plotting using a special control command comment for sphinx-gallery. See for example: https://github.com/theOehrly/Fast-F1/blob/4e2bbdea835044798cd0290a1d7780cd3d954a27/examples/plot_position_changes.py#L20

Second, it would be nice if the code could be made a bit more concise while maintaining readability. I don't have a good idea for how to this at the moment. But it is something you could think about. Maybe you have a good idea. At the moment, this is a rather long example, with lots of very similar code. Although, I understand why that is.

And finally, you need to enable support for Matplotlib animations in the sphinx gallery configuration file. See https://sphinx-gallery.github.io/stable/auto_examples/plot_8_animations.html


You can download the CI documentation build by clicking on "Details" for one of the CI jobs, then on "Summary" at the top left of that page. At the bottom you will find an "Artifacts" section, where you can download the documentation build as a zip file. Then you can check, whether everything works correctly.

**Comment by harningle** [comment]
I guess one way to make the code slightly more concise is to use a mapping. We have five axes in the animation, and this mapping tells us for each axis, what's the x, y, colour, etc.

```python
##############################################################################
# plot ratios are for how big each plot is
plot_ratios = [3, 1, 1, 1, 1]
plot_size = [15, 15]

# create 5 plots
fig, axs = plt.subplots(
    5,
    gridspec_kw={'height_ratios': plot_ratios}
)
plt.rcParams['figure.figsize'] = plot_size
ax_mapping = {
    0: {'x': 'X', 'y': 'Y', 'colour': 'red'},
    1: {'x': 'Distance', 'y': 'Speed', 'colour': 'blue'},
    2: {'x': 'Distance', 'y': 'Brake', 'colour': 'green'},
    3: {'x': 'Distance', 'y': 'RPM', 'colour': 'orange'},
    4: {'x': 'Distance', 'y': 'Throttle', 'colour': 'purple'},
}


##############################################################################
# initialize the plots with the first data point
lines = []
for ax in ax_mapping:
    lines.append(
        axs[ax].plot(
            tel[ax_mapping[ax]['x']][0],
            tel[ax_mapping[ax]['y']][0],
            color=ax_mapping[ax]['colour'],
            linestyle='-', marker='o', linewidth=2, markersize=1
        )
    )
```

Similarly, we can replace the `updateXxxx` function, as long as we know which axis and which x and y we are updating.

**Comment by theOehrly** [comment]
@harningle that makes the code more concise, but in my opinion less readable.

Given that this is only an example, wouldn't it actually be sufficient to only plot and animate one or two data channels?
After all, the example doesn't need to be (and can't be) a ready-made script for every task a user might want to accomplish.
Showing how the animation is done in principle with one or two data channels already accomplishes the goal of an example.

**Comment by harningle** [comment]
> @harningle that makes the code more concise, but in my opinion less readable.
> 
> Given that this is only an example, wouldn't it actually be sufficient to only plot and animate one or two data channels? After all, the example doesn't need to be (and can't be) a ready-made script for every task a user might want to accomplish. Showing how the animation is done in principle with one or two data channels already accomplishes the goal of an example.

Absolutely!

**Pull request closed without merging**
